## one dimensional array

In [1]:
data_list =[1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr =np.array(data_list)


In [5]:
arr

array([1, 2, 3])

In [8]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [9]:
arr2 = np.array(data_list2)

In [10]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
arr3 =np.array([1,2,3,4,5])

In [12]:
arr3

array([1, 2, 3, 4, 5])

In [13]:
arr3[0]

1

In [17]:
arr3[4]

5

In [18]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [19]:
arr2[2][2]

90

In [20]:
arr2[2,2]

90

In [21]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
np.random.randint(0,10)

4

In [33]:
np.random.randint(15)

9

In [35]:
np.random.randint(1,10,5)

array([6, 4, 7, 5, 3])

In [37]:
np.random.rand(5)

array([0.95485389, 0.46206301, 0.68795941, 0.73056916, 0.84769923])

In [38]:
np.random.randn(5)

array([-0.01694579, -0.07438516,  0.60071953,  1.45565208,  0.81698442])

In [42]:
arr =np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
newArray = np.random.randint(1,100,10)

In [46]:
newArray

array([22,  4, 91, 62, 85, 77, 73, 68, 97, 99])

In [48]:
newArray.max()

99

In [49]:
newArray.min()

4

In [50]:
newArray.sum()

678

In [51]:
newArray.mean()

67.8

In [52]:
newArray.argmax()

9

In [53]:
newArray.argmin()

1

## Determint

In [55]:
detArr = np.random.randint(1,100,25)

In [56]:
detArr

array([30, 60, 80, 36,  9, 79,  7,  6,  7, 13, 63, 37, 52,  2, 29, 58, 28,
       72, 34,  2, 49, 63, 86, 75, 85])

In [60]:
detArr = detArr.reshape(5,5)

In [61]:
detArr

array([[30, 60, 80, 36,  9],
       [79,  7,  6,  7, 13],
       [63, 37, 52,  2, 29],
       [58, 28, 72, 34,  2],
       [49, 63, 86, 75, 85]])

In [62]:
np.linalg.det(detArr)

-393287000.00000113

In [64]:
detArr2 =np.array([[1,2],[3,4]])

In [65]:
detArr2

array([[1, 2],
       [3, 4]])

In [66]:
np.linalg.det(detArr2)

-2.0000000000000004

In [67]:
round(np.linalg.det(detArr2))

-2

## Array indexes

In [72]:
arr= np.arange(1,10)

In [73]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr[2]

3

In [75]:
arr[5]

6

In [76]:
arr[1:5]

array([2, 3, 4, 5])

In [77]:
arr[:4]

array([1, 2, 3, 4])

In [78]:
arr[: :2]

array([1, 3, 5, 7, 9])

In [79]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr[:3]

array([1, 2, 3])

In [81]:
arr[:3]=25

In [82]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [83]:
arr =np.arange(1,10)

In [84]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr2=arr

In [86]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr2[:3]=10

In [88]:
arr2

array([10, 10, 10,  4,  5,  6,  7,  8,  9])

In [89]:
arr

array([10, 10, 10,  4,  5,  6,  7,  8,  9])

In [90]:
arr =np.arange(1,10)

In [91]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr2 =arr.copy()

In [93]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
arr2[:3]=25

In [95]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [96]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])