
# Why NumPy?

In [7]:
a =[1,2,3,4]
b =[2,3,4,5]
a
b

[2, 3, 4, 5]

In [8]:
a


[1, 2, 3, 4]

In [9]:
b

[2, 3, 4, 5]

In [10]:
a =[1,2,3,4]
b =[2,3,4,5]

In [11]:
ab=[]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [12]:
import numpy as np

In [13]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])


In [14]:
a*b

array([ 2,  6, 12, 20])

## properties
* **ndim**:_dimension number_
* shape: dimension information
* size :total element number
* dtype: array data type

In [15]:
import numpy as np

In [16]:
np.random.randint(10, size =10)


array([2, 4, 4, 3, 8, 7, 5, 8, 2, 5])

In [17]:
a = np.random.randint(10, size =10)

In [18]:
a.ndim

1

In [19]:
a.shape

(10,)

In [20]:
a.size

10

In [21]:
a.dtype

dtype('int32')

In [22]:
b =np.random.randint(10 , size = (3,5))

In [23]:
b

array([[5, 9, 4, 5, 8],
       [6, 9, 1, 8, 4],
       [1, 0, 3, 8, 9]])

In [24]:
b.ndim

2

In [25]:
b.shape

(3, 5)

In [26]:
b.size

15

In [27]:
b.dtype

dtype('int32')

# Reshaping

In [28]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a =np.arange(1,10)

In [31]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a.ndim

1

In [33]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
b =a.reshape((1,9))

In [35]:
b.ndim

2

# Concatenation

In [36]:
import numpy as np

In [37]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [38]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [39]:
z =np.array([7,8,9])

In [40]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## two dimensional array

In [41]:
a = np.array([[1,2,3],[4,5,6]])

In [42]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [43]:
np.concatenate([a,a],axis =0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
np.concatenate([a,a],axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Splitting

In [45]:
import numpy as np

In [46]:
x = np.array([1,2,3,4,99,3,2,1])

In [47]:
np.split(x,[3,5])

[array([1, 2, 3]), array([ 4, 99]), array([3, 2, 1])]

In [48]:
a,b,c = np.split(x,[3,5])

In [49]:
a

array([1, 2, 3])

In [50]:
b

array([ 4, 99])

In [51]:
c

array([3, 2, 1])

## Two dimensional split

In [52]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [54]:
upper,down =np.vsplit(m,[2])

In [55]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
down

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Sorting

In [57]:
import numpy as np

In [58]:
v =np.array([2,1,3,5,4])

In [59]:
v

array([2, 1, 3, 5, 4])

In [60]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [61]:
v.sort()

In [62]:
v

array([1, 2, 3, 4, 5])

In [63]:
v

array([1, 2, 3, 4, 5])

## Two dimensional Array

In [64]:
m =np.random.normal(20,5,(3,3))

In [65]:
m

array([[16.11839443, 22.46256233, 14.42366507],
       [13.8232845 , 24.19999467, 19.43433681],
       [23.54733086, 24.88801528, 14.55923434]])

In [66]:
np.sort(m,axis =0)

array([[13.8232845 , 22.46256233, 14.42366507],
       [16.11839443, 24.19999467, 14.55923434],
       [23.54733086, 24.88801528, 19.43433681]])

In [67]:
np.sort(m,axis =1)

array([[14.42366507, 16.11839443, 22.46256233],
       [13.8232845 , 19.43433681, 24.19999467],
       [14.55923434, 23.54733086, 24.88801528]])

# Access elements with Indexes 

In [68]:
import numpy as np
a =np.random.randint(10, size =10)
a

array([9, 9, 6, 9, 8, 1, 6, 2, 6, 2])

In [69]:
a[0]

9

In [70]:
a[1]

9

In [71]:
a[-1]

2

In [72]:
a[0] =100

In [73]:
a

array([100,   9,   6,   9,   8,   1,   6,   2,   6,   2])

## two dimensional array with indexes

In [81]:
m =np.random.randint(10, size =(3,5))
m

array([[3, 4, 2, 8, 9],
       [2, 7, 6, 4, 8],
       [5, 5, 3, 8, 7]])

In [82]:
m[0][0]

3

In [83]:
m[1][1]

7

In [84]:
m[1,3]

4

In [85]:
m [1,4]=99

In [86]:
m

array([[ 3,  4,  2,  8,  9],
       [ 2,  7,  6,  4, 99],
       [ 5,  5,  3,  8,  7]])

In [89]:
m [2,4] =89

In [88]:
m[1,4] =2.2

In [38]:
m

array([[2, 8, 3, 7, 6],
       [7, 9, 6, 7, 2],
       [8, 5, 4, 7, 9]])

## access elements with slicing  /Alt kume islemleri

In [90]:
import numpy as np

In [91]:
n =np.arange(20,30)
n

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [92]:
n[0:3]

array([20, 21, 22])

In [93]:
n[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [94]:
n[1::2]

array([21, 23, 25, 27, 29])

In [95]:
n[0::3]

array([20, 23, 26, 29])

In [96]:
n[2::2]

array([22, 24, 26, 28])

# two dimencional slice

In [97]:
m = np.random.randint(10, size =(5,5))

In [98]:
m

array([[6, 5, 0, 2, 6],
       [4, 7, 4, 0, 3],
       [1, 9, 0, 2, 2],
       [0, 8, 0, 5, 7],
       [7, 6, 6, 0, 1]])

In [99]:
m[:,0]

array([6, 4, 1, 0, 7])

In [100]:
m[:,4]

array([6, 3, 2, 7, 1])

In [101]:
m[0,:]

array([6, 5, 0, 2, 6])

In [102]:
m[1,:]

array([4, 7, 4, 0, 3])

In [103]:
m[0:2,0:3]

array([[6, 5, 0],
       [4, 7, 4]])

In [104]:
m[::,0:2]

array([[6, 5],
       [4, 7],
       [1, 9],
       [0, 8],
       [7, 6]])

In [105]:
m[1:3,0:2]

array([[4, 7],
       [1, 9]])

## acceseseble elements with Fancy index

In [106]:
import numpy as np
v =np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [107]:
v[1]

3

In [108]:
v[3]

9

In [109]:
v[5]

15

## looking at together

In [110]:
[v[1],v[5],v[9]]

[3, 15, 27]

In [111]:
all_fetch =[1,3,5]

In [112]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [113]:
v[all_fetch]

array([ 3,  9, 15])

## two dimensional fancy

In [114]:
k =np.arange(9).reshape((3,3))

In [115]:
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
row =np.array([0,1])
column =np.array([1,2])

In [117]:
k[row,column]

array([1, 5])

## simple indexes with fancy index

In [118]:
m

array([[6, 5, 0, 2, 6],
       [4, 7, 4, 0, 3],
       [1, 9, 0, 2, 2],
       [0, 8, 0, 5, 7],
       [7, 6, 6, 0, 1]])

In [119]:
m[0,[1,2]]

array([5, 0])

## slice with fancy

In [120]:
m[0:,[1,2]]

array([[5, 0],
       [7, 4],
       [9, 0],
       [8, 0],
       [6, 6]])