# Create PANDAS Series

In [1]:
import pandas as pd

In [2]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
series = pd.Series([1,2,3,4,5])

In [4]:
type(series)

pandas.core.series.Series

In [5]:
series.axes

[RangeIndex(start=0, stop=5, step=1)]

In [6]:
series.dtype

dtype('int64')

In [7]:
series.size

5

In [8]:
series.ndim

1

In [9]:
series.values

array([1, 2, 3, 4, 5], dtype=int64)

In [11]:
series.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
series.tail()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
series.tail(2)

3    4
4    5
dtype: int64

## index naming

In [14]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [15]:
pd.Series([99,22,332,94,5],index =[1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [17]:
pd.Series([99,22,332,94,5],index =["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [18]:
series =pd.Series([99,22,332,94,5],index =["a","b","c","d","e"])

In [19]:
series["a"]

99

In [21]:
series["a":"c"]

a     99
b     22
c    332
dtype: int64

## create list on the dictionary

In [23]:
dict=pd.Series({"reg":10,"log":11,"cart":12})

In [24]:
dict

reg     10
log     11
cart    12
dtype: int64

In [25]:
type(dict)

pandas.core.series.Series

In [26]:
dictsample=pd.Series(dict)

In [27]:
dictsample

reg     10
log     11
cart    12
dtype: int64

## concanatation

In [31]:
pd.concat ([dict,dict])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

## element operations

In [33]:
import numpy as np
import pandas as pd


In [36]:
a =np.array([1,2,33,44,55])
series =pd.Series(a)
series

0     1
1     2
2    33
3    44
4    55
dtype: int32

In [37]:
series[0]

1

In [39]:
series[0:3]

0     1
1     2
2    33
dtype: int32

In [40]:
series =pd.Series([121,200,150,99],index =["reg","log","cart","rf"])

In [41]:
series

reg     121
log     200
cart    150
rf       99
dtype: int64

In [42]:
series.index

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

In [43]:
series.keys

<bound method Series.keys of reg     121
log     200
cart    150
rf       99
dtype: int64>

In [44]:
list(series.items())

[('reg', 121), ('log', 200), ('cart', 150), ('rf', 99)]

In [46]:
series.values

array([121, 200, 150,  99], dtype=int64)

## element query

In [47]:
"reg" in series

True

In [48]:
"a" in series

False

In [49]:
series["reg"]

121

# Fancy element

In [51]:
series[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [52]:
series["reg"]=131

In [53]:
series["reg"]

131

In [54]:
series["reg":"log"]

reg    131
log    200
dtype: int64

# Create Pandas Data Frame

In [55]:
import pandas as pd

In [56]:
l =[1,2,39,67,90]

In [57]:
l

[1, 2, 39, 67, 90]

In [58]:
pd.DataFrame(l,columns =["variable name"])

variable name
0              1
1              2
2             39
3             67
4             90

In [61]:
import numpy as np
m =np.arange(1,10).reshape((3,3,))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
pd.DataFrame(m,columns =["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

## df namelys

In [63]:
df = pd.DataFrame(m,columns =["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [65]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [66]:
type(df)

pandas.core.frame.DataFrame

In [67]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['var1', 'var2', 'var3'], dtype='object')]

In [68]:
df.shape

(3, 3)

In [69]:
df.ndim

2

In [70]:
df.size

9

In [71]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
type(df.values)

numpy.ndarray

In [75]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [76]:
df.tail(1)

var1  var2  var3
2     7     8     9

In [77]:
a =np.array([1,2,3,4,5])

In [78]:
pd.DataFrame(a,columns =["var1"])

var1
0     1
1     2
2     3
3     4
4     5