## Pandas DadaFrame Element Process

In [9]:
import numpy as np
import pandas as pd


In [2]:
s1 = np.random.randint(10, size =5)
s2 = np.random.randint(10, size =5)
s3 = np.random.randint(10, size =5)

In [3]:
s1

array([9, 1, 2, 5, 8])

In [4]:
s2

array([6, 9, 7, 3, 5])

In [5]:
s3

array([2, 8, 0, 1, 9])

In [6]:
dictnry ={"var1":s1,"var2":s2,"var3":s3}

In [7]:
dictnry

{'var1': array([9, 1, 2, 5, 8]),
 'var2': array([6, 9, 7, 3, 5]),
 'var3': array([2, 8, 0, 1, 9])}

In [10]:

df = pd.DataFrame(dictnry)

In [11]:
df

var1  var2  var3
0     9     6     2
1     1     9     8
2     2     7     0
3     5     3     1
4     8     5     9

* Rows 0 to 1

In [14]:
df[0:1]

var1  var2  var3
0     9     6     2

* change index

In [15]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
df.index = ["z","x","c","v","b"]

In [17]:
df

var1  var2  var3
z     9     6     2
x     1     9     8
c     2     7     0
v     5     3     1
b     8     5     9

* Making a selection for index

In [19]:
df["c":"b"]

var1  var2  var3
c     2     7     0
v     5     3     1
b     8     5     9

# silme

In [20]:
df.drop("x",axis=0)

var1  var2  var3
z     9     6     2
c     2     7     0
v     5     3     1
b     8     5     9

In [22]:
df

var1  var2  var3
z     9     6     2
x     1     9     8
c     2     7     0
v     5     3     1
b     8     5     9

In [23]:
df.drop("x",axis=0,inplace =True)

In [24]:
df

var1  var2  var3
z     9     6     2
c     2     7     0
v     5     3     1
b     8     5     9

In [25]:
df

var1  var2  var3
z     9     6     2
c     2     7     0
v     5     3     1
b     8     5     9

# Fancy

In [28]:
l= ["c","b"]

In [29]:
df.drop(l,axis =0)

var1  var2  var3
z     9     6     2
v     5     3     1

# for variable 

In [31]:
"var1" in df

True

In [34]:
["var1","var4","var2"]

['var1', 'var4', 'var2']

In [35]:
for i in l:
    print(i in df)

False
False


In [36]:
df

var1  var2  var3
z     9     6     2
c     2     7     0
v     5     3     1
b     8     5     9

In [37]:
df["var1"]

z    9
c    2
v    5
b    8
Name: var1, dtype: int32

In [38]:
df ["var4"] = df["var1"]/df["var2"]

In [39]:
df

var1  var2  var3      var4
z     9     6     2  1.500000
c     2     7     0  0.285714
v     5     3     1  1.666667
b     8     5     9  1.600000

# delte variable

In [40]:
df.drop("var4",axis =1)

var1  var2  var3
z     9     6     2
c     2     7     0
v     5     3     1
b     8     5     9

In [41]:
df

var1  var2  var3      var4
z     9     6     2  1.500000
c     2     7     0  0.285714
v     5     3     1  1.666667
b     8     5     9  1.600000

In [42]:
df.drop("var4",axis =1 ,inplace =True)

In [43]:
df

var1  var2  var3
z     9     6     2
c     2     7     0
v     5     3     1
b     8     5     9

In [44]:
l =["var1","var2"]

In [45]:
df.drop(l,axis =1 )

var3
z     2
c     0
v     1
b     9